# Support the author by using the funding links below.
# Developed and maintained by Amaan Mohib with the help of awesome contributors.
# GitHub Sponsors: https://github.com/sponsors/amaan-mohib
# Buy Me a Coffee: https://buymeacoffee.com/amaan.mohib

github: amaan-mohib
buy_me_a_coffee: amaan.mohib
